name: qora
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  go_router: ^17.0.1
  lottie: ^3.3.2
  toastification: ^3.0.3

  # Networking & Dependency Injection
  http: ^1.6.0

  # Storage & Data
  flutter_dotenv: ^5.2.1

  # State management & Core
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  intl: ^0.20.2

  # WebRTC & Voice Assistant
  flutter_webrtc: ^0.12.8
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation Tools
  freezed: ^2.5.2                    
  json_serializable: ^6.8.0         

  # Testing packages
  mocktail: ^1.0.4                   

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lotties/
    - lib/features/home/data/mock/
    - lib/features/search/mock/
    - lib/features/hotel_detail/mock/
    - lib/features/booking/mock/
    - lib/features/hotel_list/data/mock/
    - lib/features/profile/mock/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
    - family: PermanentMarker
      fonts:
        - asset: assets/font/PermanentMarker-Regular.ttf
          weight: 400
